# Modified Zenburn theme for better terminal readability
# Colors (Zenburn)
# Orginally designed by jnurmine for vim.

# Default colors
[colors.primary]
background = '#3F3F3F'
foreground = '#DCDCCC'

# Normal colors
[colors.normal]
black   = '#262626'
red     = '#AC7373'
green   = '#93B3A3'
yellow  = '#C3BF9F'
blue    = '#7CB8BB'  # https://gist.github.com/dlebauer/1486859#file-zenburn-el-L83
magenta = '#DC8CC3'
cyan    = '#8CD0D3'
white   = '#DCDCCC'

# Bright colors
[colors.bright]
black   = '#333333'
red     = '#DCA3A3'
green   = '#CBECD0'
yellow  = '#F8F893'
blue    = '#8CD0D3'
magenta = '#EC93D3'
cyan    = '#93E0E3'
white   = '#FFFFFF'
