import = [
    "~/.config/alacritty/themes/themes/zenburn_improved.toml"
]

[font]
size = 14

[font.normal]
# family = "IosevkaNerdFont"
family = "SourceCodePro"

[window]

opacity=0.9
padding.x=10
padding.y=10
